// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOy3l7OhLJiNm6YyrY83JAMZVD3G5qqA4',
    appId: '1:311893434098:web:4c5126fb8ddd126bd27a6b',
    messagingSenderId: '311893434098',
    projectId: 'spotifyclone0821',
    authDomain: 'spotifyclone0821.firebaseapp.com',
    storageBucket: 'spotifyclone0821.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVpVn26Z_JCVnje9p7iXgu8pQIkzVexUM',
    appId: '1:311893434098:android:b72b34b2f4d0ff06d27a6b',
    messagingSenderId: '311893434098',
    projectId: 'spotifyclone0821',
    storageBucket: 'spotifyclone0821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwW5Kk8wVCKXUijUgF1VVEDfFnutPwqFM',
    appId: '1:311893434098:ios:51c9c95d55d1d936d27a6b',
    messagingSenderId: '311893434098',
    projectId: 'spotifyclone0821',
    storageBucket: 'spotifyclone0821.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwW5Kk8wVCKXUijUgF1VVEDfFnutPwqFM',
    appId: '1:311893434098:ios:51c9c95d55d1d936d27a6b',
    messagingSenderId: '311893434098',
    projectId: 'spotifyclone0821',
    storageBucket: 'spotifyclone0821.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOy3l7OhLJiNm6YyrY83JAMZVD3G5qqA4',
    appId: '1:311893434098:web:035ebc0deeda3f5bd27a6b',
    messagingSenderId: '311893434098',
    projectId: 'spotifyclone0821',
    authDomain: 'spotifyclone0821.firebaseapp.com',
    storageBucket: 'spotifyclone0821.firebasestorage.app',
  );
}
